### ISSUE TITLE
Расчет LTL

### ISSUE THREAD

**Issue by AlexeyZheltov** [AlexeyZheltov/DomesticTransport#16]
По Еревану и Нурсултану при расчете стоимости доставки использовать брутто вес.
Стоимость рассчитывается по формуле

Брутто вес * Удельная цена за 100 кг + Кол-во доп точек * Стоимость доп точки

**Comment by AlekseyEvseev** [comment]
Уточню 
вес 1345 цена 5250 
результат 13,45 * 5250 или 14 * 5250 ? цена за 100 кг подразумевает округление?
делаю 1 вариант как в задаче написано
доп. точки для QB -6500 для GTLS - 2500 судя по их таблице

**Comment by AlexeyZheltov** [comment]
@AlekseyEvseev   Без округлений они говорили
